### ISSUE TITLE
Update Subgraph Addresses

### ISSUE THREAD

**Issue by 0xCoDeFi** [centfinance/Symmetric.WebInterface-v2#18]
**Describe the bug**
update weightedpoolfactory/weightedpool2tokenfactory/vault addresses and re-deploy subgraph

**Comment by tqmvt** [comment]
Closed by commit [53c8...69e2](https://github.com/centfinance/Symmetric.Subgraph-v2/commit/53c8609fe7f1f5a9b0ac6e742a65dac9c5ac69e2)
