### ISSUE TITLE
Restore trade/invest button location

### ISSUE THREAD

**Issue by 0xCoDeFi** [centfinance/Symmetric.WebInterface-v2#19]
Restore the position of trade/invest buttons and their size.

**Comment by tqmvt** [comment]
@talentdev2020 contact me when you start working on it.

We can make the pools/swap `buttons` to `menu items`. What do you think @0xCoDeFi ?

**Comment by aristidesgpg** [comment]
@launchdex Could you tell me where I can find these buttons?

**Comment by tqmvt** [comment]
Fixed by commit [2a40c66...](https://github.com/centfinance/Symmetric.WebInterface-v2/commit/2a40c66f2167d7c0a69fdd4292ce7bee775c4e3c)
